# Site settings
title: Jacob Bokor
description: Jacob Bokor's personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jacob Bokor
user_description: 
user_title: Student, Programmer, and Maker
email: jacob@jacobbokor.com
twitter_username: PwnKitteh
github_username:  PwnKitteh
#Gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
